# Spring Application Name
spring.application.name=loan-engine-backend

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_engine_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# SQL Init Configuration
spring.sql.init.mode=never

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bharathibera300@gmail.com
spring.mail.password=gbefraerbkzqrkiw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Server Configuration
server.port=8080

# App Custom JWT Properties
app.jwt.secret=${JWT_SECRET:LoanEngineSecretKeyForJWTTokenGenerationMustBe256BitsLongMinimum!!}
app.jwt.expiration-ms=86400000

# App Custom OTP Properties
app.otp.expiry-minutes=5
app.otp.length=6

# App Custom Mail Properties
app.mail.from=bharathibera300@gmail.com
app.mail.dev-log-only=false

# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:3000
